# Generated by Django 5.0.4 on 2024-04-29 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_alter_director_age_alter_movie_year_of_release_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='watchlist_app.movie'),
        ),
        migrations.AlterField(
            model_name='movieactor',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='watchlist_app.movie'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='watchlist_app.movie'),
        ),
    ]
